name: Run LAOWANG Sign
on:
  push:
  workflow_dispatch:
  schedule:
    - cron: '15 0 * * *'

jobs:
  run:
    runs-on: ubuntu-latest
    env:
      LAOWANG_HOSTNAME: ${{ secrets.LAOWANG_HOSTNAME }}
      LAOWANG_USERNAME: ${{ secrets.LAOWANG_USERNAME }}
      LAOWANG_PASSWORD: ${{ secrets.LAOWANG_PASSWORD }}
      LAOWANG_COOKIE: ${{ secrets.LAOWANG_COOKIE }}
      BARKURL: ${{ secrets.BARKURL }}
      BARKKEY: ${{ secrets.BARKKEY }}
      SENDCHANNEL: ${{ secrets.SENDCHANNEL }}

    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'
          cache: 'pip'
      - run: pip install -r requirements.txt
      - name: Run laowang.py
        run: python laowang.py
